(*
 * This is an autogenerated file. Do not edit.
 * It was created using instantiate_laws.py.
 * It checks whether the other autogenerated files are up-to-date.
 *)

theory Check_Autogenerated_Files
  (* These imports are not actually needed, but in jEdit, they will conveniently trigger a re-execution of the checking code below upon changes. *)
  imports Laws_Classical Laws_Quantum Laws_Complement_Quantum
begin

ML \<open>
let
  fun check kind file expected = let
    val content = File.read (Path.append (Resources.master_directory \<^theory>) (Path.basic file))
    val hash = SHA1.digest content |> SHA1.rep
    in
      if hash = expected then () else
      error (kind ^ " file " ^ file ^ " has changed.\nPlease run \"python3 instantiate_laws.py\" to recreated autogenerated files.\nExpected SHA1 hash " ^ expected ^ ", got " ^ hash)
    end
in
  check "Source" "Axioms_Classical.thy" "72388b1ddd9b0570c9f0761063a13e5e777551e3";
  check "Source" "Axioms_Quantum.thy" "cafbf1d57993d6e6064a04e0db32c3e354320300";
  check "Source" "Laws.thy" "83f19ec3f5710b3b914a5d69ecee9a202479b0c3";
  check "Source" "Laws_Complement.thy" "5ba70f38590214499d1dbf91e09c92b45d18365a";
  check "Generated" "Laws_Classical.thy" "74f6acabbc93f6885969d4630adda5f25ad26feb";
  check "Generated" "Laws_Complement_Quantum.thy" "50c6edbbd9d6cd1b7e55dd8a2e233d4874962575";
  check "Generated" "Laws_Quantum.thy" "ef1832567324b54a2855a8f09ecfe448575b77a9"
end
\<close>

end
