(*
 * This is an autogenerated file. Do not edit.
 * It was created using instantiate_laws.py.
 * It checks whether the other autogenerated files are up-to-date.
 *)

theory Check_Autogenerated_Files
  (* These imports are not actually needed, but in jEdit, they will conveniently trigger a re-execution of the checking code below upon changes. *)
  imports Laws_Classical Laws_Quantum Laws_Complement_Quantum
begin

ML \<open>
let
  fun check kind file expected = let
    val content = File.read (Path.append (Resources.master_directory \<^theory>) (Path.basic file))
    val hash = SHA1.digest content |> SHA1.rep
    in
      if hash = expected then () else
      error (kind ^ " file " ^ file ^ " has changed.\nPlease run \"python3 instantiate_laws.py\" to recreated autogenerated files.\nExpected SHA1 hash " ^ expected ^ ", got " ^ hash)
    end
in
  check "Source" "Axioms_Classical.thy" "e3c6ca3fa815506631517ea5d682c23c08f4ed4f";
  check "Source" "Axioms_Quantum.thy" "0d80aad43836f63fd30c93c5ad1ed2dfc4af72a9";
  check "Source" "Laws.thy" "1db2088f827e04309e9ba20810c3a274cebeabab";
  check "Source" "Laws_Complement.thy" "91721de3c65892ae6f11f37c3740414cc147070e";
  check "Generated" "Laws_Classical.thy" "3d37a81779a1277e9ca5bb387eab03c3d401e691";
  check "Generated" "Laws_Complement_Quantum.thy" "0b686903f139d414a6f5cc754fa1397780784563";
  check "Generated" "Laws_Quantum.thy" "f135807fac134b786da7c8b9c479147c4d2d9780"
end
\<close>

end
