(*
 * This is an autogenerated file. Do not edit.
 * It was created using instantiate_laws.py.
 * It checks whether the other autogenerated files are up-to-date.
 *)

theory Check_Autogenerated_Files
  (* These imports are not actually needed, but in jEdit, they will conveniently trigger a re-execution of the checking code below upon changes. *)
  imports Laws_Classical Laws_Quantum Laws_Complement_Quantum
begin

ML \<open>
let
  fun check kind file expected = let
    val content = File.read (Path.append (Resources.master_directory \<^theory>) (Path.basic file))
    val hash = SHA1.digest content |> SHA1.rep
    in
      if hash = expected then () else
      error (kind ^ " file " ^ file ^ " has changed.\nPlease run \"python3 instantiate_laws.py\" to recreated autogenerated files.\nExpected SHA1 hash " ^ expected ^ ", got " ^ hash)
    end
in
  check "Source" "Axioms_Classical.thy" "f4a0dac97bed23ec5b7c4cbf779f8eb2a12aa488";
  check "Source" "Axioms_Quantum.thy" "691377a706446b8a709a856e97ed0c51884d888c";
  check "Source" "Laws.thy" "04070e03e9ad6a7089610d74c6e8ef960f42eae7";
  check "Source" "Laws_Complement.thy" "6065101853fa432ca4bd6fd3113315e856e21ecb";
  check "Generated" "Laws_Classical.thy" "50572df7f9af54b7f32dbb4a9e673f3c1e394a59";
  check "Generated" "Laws_Complement_Quantum.thy" "f611effded462febdd46d12773f9b323b2205480";
  check "Generated" "Laws_Quantum.thy" "727ef21374d815fe018bd430a369f023ce79e843"
end
\<close>

end
